### ISSUE TITLE
Language Trans

### ISSUE THREAD

**Issue by wcdfilll** [Tsubasa6848/Advancements-Release#3]
[en_US.zip](https://github.com/Tsubasa6848/Advancements-Release/files/11395732/en_US.zip)

**Comment by Tsubasa6848** [comment]
Thanks for your translation.

You may use pull request instead of issues to update the translation.

In addition, I found something different from the original language pack in Minecraft: Java Edition. Is it intentional?

**Comment by Tsubasa6848** [comment]
for example:

Planting Seeds -> A Seedy Place
Conquering the Skies -> Sky`s the Limit
Row a Boat with a Goat! -> Whatever Floats Your Goat!

and so on..
